# Generated by Django 2.1.2 on 2018-11-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='creat_time',
            new_name='created_time',
        ),
    ]
